### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [HassenPy/django-pdb#51]
Hello, I'd like to know if the project is still active. If not, I'd love to be a maintainer and update and add new features.

**Comment by HassenPy** [comment]
Hey @alexandrebarbaruiva, and apologies 🙏 for those interested in this repo, i originally took it with plans for adding features and refactoring, however life happened and didn't have the luxury to work on it.
Would love to pass this project, but I'm not the "owner" of this project, technically i can pass you the repo, but you have to check with @tomchristie so that he adds you to pypi.

**Comment by lovelydinosaur** [comment]
It looks like both myself and Hassan have maintainership rights on the PyPI repo.
Personally I'm more than happy to hand it over to anyone interested, sure.
